# Generated by Django 3.1.5 on 2021-01-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointRequests', '0002_pointrequest_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='rewardRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('reward', models.CharField(max_length=69)),
                ('date', models.CharField(max_length=9)),
            ],
        ),
    ]
