# Generated by Django 2.0.7 on 2021-01-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jennifer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('task', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=1024)),
                ('points', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pandora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('task', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=1024)),
                ('points', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Violet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('task', models.CharField(max_length=256)),
                ('remarks', models.CharField(max_length=1024)),
                ('points', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
    ]
