# Generated by Django 2.0.7 on 2021-01-02 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_invalid_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invalid_password',
            new_name='invalid_passwords',
        ),
    ]
