# Generated by Django 2.0.7 on 2021-01-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('limitations', models.CharField(max_length=256)),
                ('pointValue', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
